Automatically update "Last Updated" in README
mrpond/BlockTheSpot pull request #365
Opened 2022-04-22 17:58 UTC by Araxeus

this GitHub action is run whenever source code change, will automatically update the "Last updated" in the readme

sample commit here:
https://github.com/Araxeus/BlockTheSpot/commit/76bfa6a57734b81013e22464fae2d77a0ef9a8fb

2022-04-22 18:14 UTC, Nuzair46 requested changes
@Araxeus Please look into the review.

2022-04-22 18:14 UTC, Nuzair46 commented on .github/workflows/last-updated.yml
> +    paths: [install.ps1, src/**, BlockTheSpot.bat]
Do not include `install.ps1` and `BlockTheSpot.bat` as they are not related to the source of the release. Only listen to the src folder.

2022-04-22 18:14 UTC, Nuzair46 commented on .github/workflows/last-updated.yml
> +        # sed -i "/<strong>Last updated:<\/strong> /s|> .*<br>|> $(date +"%d %B %Y")<br>|" README.md
Please remove this comment if its unwanted.

2022-04-22 18:14 UTC, Nuzair46 commented on .github/workflows/last-updated.yml
> +          git commit -m "[github-actions] update 'Last updated'"
Please add `[skip ci]` tag in the beginning of the commit message to avoid appveyor building the source again.
If appveyor skips this with `[github-actions]`, then ok.

2022-04-22 18:15 UTC, Nuzair46 commented
@mrpond, Please review.

2022-04-22 18:22 UTC, Araxeus commented on .github/workflows/last-updated.yml
> +    paths: [install.ps1, src/**, BlockTheSpot.bat]
are you sure `BlockTheSpot.bat` shouldn't be included?

that file actually contains relevant changes, like Remove "Upgrade" Button  Remove "Ad Placeholder" etc

2022-04-22 18:28 UTC, Araxeus commented on .github/workflows/last-updated.yml
> +        # sed -i "/<strong>Last updated:<\/strong> /s|> .*<br>|> $(date +"%d %B %Y")<br>|" README.md
I wanted to see if you maybe preferred the 2nd version, but ill remove it now

2022-04-22 18:32 UTC, Nuzair46 commented on .github/workflows/last-updated.yml
> +    paths: [install.ps1, src/**, BlockTheSpot.bat]
@Araxeus, Install.ps1 is not related to BlockTheSpot release. And it is not a necessary file. It will be confusing for users who don't use the script and manually install the release. Also we are not versioning the install.ps1 and it always runs as latest on users end, so it doesn't need to be included.

2022-04-22 18:32 UTC, Araxeus commented on .github/workflows/last-updated.yml
> +          git commit -m "[github-actions] update 'Last updated'"
"[skip ci]-[github-actions] update 'Last updated'"

looks kinda weird, how would  you want it?

2022-04-22 18:33 UTC, Nuzair46 commented on .github/workflows/last-updated.yml
> +        # sed -i "/<strong>Last updated:<\/strong> /s|> .*<br>|> $(date +"%d %B %Y")<br>|" README.md
@Araxeus You can keep anyone of the line, For me, the second line seems more readable.

2022-04-22 18:37 UTC, Nuzair46 commented on .github/workflows/last-updated.yml
> +          git commit -m "[github-actions] update 'Last updated'"
`"[skip ci] [automated] update README.md"`

2022-04-22 18:40 UTC, Nuzair46 commented on .github/workflows/last-updated.yml
> +          git commit -m "[github-actions] update 'Last updated'"
@Araxeus use the above format. Lets keep the action tag.

2022-04-22 18:45 UTC, Araxeus commented
I've amended the commit with all changes requested and tested the action to see that it still works fine

changed the date in the readme:
https://github.com/Araxeus/BlockTheSpot/commit/00e69e8825b757edf0cb1af260ddcafdab65b8ca
manually ran workflow:
https://github.com/Araxeus/BlockTheSpot/actions/runs/2209461022
GitHub action updated the date:
https://github.com/Araxeus/BlockTheSpot/commit/1f22326129bedccc34f0ab902e25510e4e95e52b

2022-04-22 18:48 UTC, Nuzair46 approved these changes
@Araxeus LGTM, Thanks for the contribution.

2022-04-22 18:48 UTC, Nuzair46 commented
@mrpond , Please review and merge once done.

2022-04-24 07:55 UTC, merged

2022-04-24 15:49 UTC, Araxeus commented
@Nuzair46 
I see you executed the workflow manually and it failed?

https://github.com/mrpond/BlockTheSpot/actions/runs/2214927402

I must say, I don't understand the error here
```
The hosted runner: Hosted Agent lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

2022-04-25 13:24 UTC, Nuzair46 commented
@Araxeus yea it seems like it. A rerun fixed it.